# Generated by Django 5.0.1 on 2024-04-12 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='specialisation',
            new_name='specialization',
        ),
    ]
